# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/TEMP/INF3610/Labo4/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_sobel_filter_0_0_1/design_1_sobel_filter_0_0.xci
# IP: The module: 'design_1_sobel_filter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/TEMP/INF3610/Labo4/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_sobel_filter_0_0_1/constraints/sobel_filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sobel_filter_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/TEMP/INF3610/Labo4/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_sobel_filter_0_0_1/design_1_sobel_filter_0_0.xci
# IP: The module: 'design_1_sobel_filter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/TEMP/INF3610/Labo4/lab4/lab4.srcs/sources_1/bd/design_1/ip/design_1_sobel_filter_0_0_1/constraints/sobel_filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sobel_filter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
