// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sobel_filter,hls_ip_2017_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=4174340,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=3449,HLS_SYN_LUT=2550}" *)

module sobel_filter (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 26'd1;
parameter    ap_ST_fsm_state2 = 26'd2;
parameter    ap_ST_fsm_state3 = 26'd4;
parameter    ap_ST_fsm_state4 = 26'd8;
parameter    ap_ST_fsm_state5 = 26'd16;
parameter    ap_ST_fsm_state6 = 26'd32;
parameter    ap_ST_fsm_state7 = 26'd64;
parameter    ap_ST_fsm_state8 = 26'd128;
parameter    ap_ST_fsm_state9 = 26'd256;
parameter    ap_ST_fsm_state10 = 26'd512;
parameter    ap_ST_fsm_state11 = 26'd1024;
parameter    ap_ST_fsm_state12 = 26'd2048;
parameter    ap_ST_fsm_state13 = 26'd4096;
parameter    ap_ST_fsm_state14 = 26'd8192;
parameter    ap_ST_fsm_state15 = 26'd16384;
parameter    ap_ST_fsm_state16 = 26'd32768;
parameter    ap_ST_fsm_state17 = 26'd65536;
parameter    ap_ST_fsm_state18 = 26'd131072;
parameter    ap_ST_fsm_state19 = 26'd262144;
parameter    ap_ST_fsm_pp0_stage0 = 26'd524288;
parameter    ap_ST_fsm_pp0_stage1 = 26'd1048576;
parameter    ap_ST_fsm_state27 = 26'd2097152;
parameter    ap_ST_fsm_state28 = 26'd4194304;
parameter    ap_ST_fsm_state29 = 26'd8388608;
parameter    ap_ST_fsm_state30 = 26'd16777216;
parameter    ap_ST_fsm_state31 = 26'd33554432;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [25:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] inter_pix;
wire   [31:0] out_pix;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state3;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state10;
wire   [0:0] tmp_2_fu_462_p2;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1_flag00000000;
reg   [0:0] tmp_8_reg_1130;
reg    gmem2_blk_n_AW;
wire    ap_CS_fsm_state19;
reg    gmem2_blk_n_W;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_pp0_stage0_flag00000000;
reg    gmem2_blk_n_B;
wire    ap_CS_fsm_state31;
wire    gmem_AWREADY;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [31:0] gmem_ARADDR;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [7:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg    gmem2_AWVALID;
wire    gmem2_AWREADY;
reg    gmem2_WVALID;
wire    gmem2_WREADY;
wire   [31:0] gmem2_WDATA;
wire    gmem2_ARREADY;
wire    gmem2_RVALID;
wire   [31:0] gmem2_RDATA;
wire    gmem2_RLAST;
wire   [0:0] gmem2_RID;
wire   [0:0] gmem2_RUSER;
wire   [1:0] gmem2_RRESP;
wire    gmem2_BVALID;
reg    gmem2_BREADY;
wire   [1:0] gmem2_BRESP;
wire   [0:0] gmem2_BID;
wire   [0:0] gmem2_BUSER;
reg   [10:0] row_assign_reg_358;
reg   [7:0] reg_369;
reg    ap_block_state10;
reg    ap_block_state21_pp0_stage1_iter0;
wire    ap_block_state23_pp0_stage1_iter1;
wire    ap_block_state25_pp0_stage1_iter2;
reg    ap_block_pp0_stage1_flag00011001;
reg   [31:0] inter_pix_read_reg_1023;
wire   [31:0] tmp_13_fu_389_p1;
reg   [31:0] tmp_13_reg_1029;
wire   [1:0] tmp_6_fu_429_p2;
reg   [1:0] tmp_6_reg_1037;
wire    ap_CS_fsm_state2;
wire   [0:0] cond_fu_435_p2;
reg   [0:0] cond_reg_1042;
wire   [0:0] tmp_fu_423_p2;
reg   [31:0] gmem_addr_reg_1046;
wire   [10:0] i_1_fu_468_p2;
reg   [10:0] i_1_reg_1055;
reg   [10:0] lineBuffer_0_addr_reg_1060;
reg   [10:0] lineBuffer_1_addr_reg_1065;
wire   [10:0] i_2_fu_540_p2;
reg   [10:0] i_2_reg_1073;
wire    ap_CS_fsm_state12;
wire   [1:0] tmp_45_fu_558_p1;
reg   [1:0] tmp_45_reg_1078;
wire   [0:0] tmp_1_fu_534_p2;
wire   [0:0] tmp1_fu_562_p2;
reg   [0:0] tmp1_reg_1086;
wire   [31:0] tmp_47_fu_572_p2;
reg   [31:0] tmp_47_reg_1091;
reg   [31:0] gmem_addr_1_reg_1096;
wire   [1:0] tmp_44_fu_592_p1;
reg   [1:0] tmp_44_reg_1102;
reg    ap_sig_ioackin_gmem2_AWREADY;
wire   [1:0] tmp_19_0_t_fu_596_p2;
reg   [1:0] tmp_19_0_t_reg_1106;
wire   [1:0] tmp_19_2_t_fu_601_p2;
reg   [1:0] tmp_19_2_t_reg_1113;
wire   [11:0] row_assign_cast_fu_620_p1;
reg   [11:0] row_assign_cast_reg_1125;
wire    ap_block_state20_pp0_stage0_iter0;
wire    ap_block_state22_pp0_stage0_iter1;
wire    ap_block_state24_pp0_stage0_iter2;
wire    ap_block_state26_pp0_stage0_iter3;
reg    ap_sig_ioackin_gmem2_WREADY;
reg    ap_block_pp0_stage0_flag00011001;
wire   [0:0] tmp_8_fu_624_p2;
wire   [10:0] j_fu_630_p2;
reg   [10:0] j_reg_1134;
wire   [0:0] or_cond2_fu_654_p2;
reg   [0:0] or_cond2_reg_1140;
reg   [0:0] ap_reg_pp0_iter1_or_cond2_reg_1140;
reg   [0:0] ap_reg_pp0_iter2_or_cond2_reg_1140;
reg   [10:0] lineBuffer_0_addr_2_reg_1146;
reg   [10:0] lineBuffer_1_addr_2_reg_1152;
reg   [10:0] lineBuffer_2_addr_1_reg_1158;
reg   [10:0] lineBuffer_3_addr_1_reg_1164;
wire   [7:0] tmp_18_fu_672_p6;
reg   [7:0] tmp_18_reg_1190;
wire   [7:0] tmp_24_fu_692_p6;
reg   [7:0] tmp_24_reg_1215;
wire   [7:0] lineBuffer_0_q0;
reg   [7:0] lineBuffer_0_load_2_reg_1220;
reg    ap_enable_reg_pp0_iter1;
wire   [7:0] lineBuffer_1_q0;
reg   [7:0] lineBuffer_1_load_2_reg_1226;
wire   [7:0] lineBuffer_2_q1;
reg   [7:0] lineBuffer_2_load_2_reg_1232;
wire   [7:0] lineBuffer_3_q1;
reg   [7:0] lineBuffer_3_load_2_reg_1238;
wire   [8:0] x_weight_0_2_fu_739_p2;
reg   [8:0] x_weight_0_2_reg_1244;
wire   [7:0] tmp_21_fu_745_p6;
reg   [7:0] tmp_21_reg_1249;
wire   [8:0] tmp3_fu_758_p2;
reg   [8:0] tmp3_reg_1254;
wire   [7:0] tmp_23_fu_764_p6;
reg   [7:0] tmp_23_reg_1259;
wire   [10:0] x_weight_2_2_fu_897_p2;
reg   [10:0] x_weight_2_2_reg_1264;
wire   [10:0] y_weight_2_2_fu_903_p2;
reg   [10:0] y_weight_2_2_reg_1269;
wire   [7:0] tmp_27_fu_909_p2;
reg   [7:0] tmp_27_reg_1274;
wire   [7:0] tmp_51_fu_915_p1;
reg   [7:0] tmp_51_reg_1280;
wire   [7:0] tmp_15_fu_953_p2;
reg   [7:0] tmp_15_reg_1286;
wire   [7:0] val_fu_1000_p3;
reg   [7:0] val_reg_1293;
wire   [10:0] lastLine_2_fu_1017_p2;
reg   [10:0] lastLine_2_reg_1301;
wire    ap_CS_fsm_state27;
reg    ap_block_pp0_stage0_flag00011011;
reg    ap_condition_pp0_exit_iter0_state20;
reg    ap_block_pp0_stage1_flag00011011;
reg    ap_enable_reg_pp0_iter2;
reg   [10:0] lineBuffer_0_address0;
reg    lineBuffer_0_ce0;
reg    lineBuffer_0_we0;
reg   [10:0] lineBuffer_0_address1;
reg    lineBuffer_0_ce1;
reg    lineBuffer_0_we1;
wire   [7:0] lineBuffer_0_q1;
reg   [10:0] lineBuffer_1_address0;
reg    lineBuffer_1_ce0;
reg    lineBuffer_1_we0;
reg   [10:0] lineBuffer_1_address1;
reg    lineBuffer_1_ce1;
reg    lineBuffer_1_we1;
wire   [7:0] lineBuffer_1_q1;
reg   [10:0] lineBuffer_2_address0;
reg    lineBuffer_2_ce0;
wire   [7:0] lineBuffer_2_q0;
reg   [10:0] lineBuffer_2_address1;
reg    lineBuffer_2_ce1;
reg    lineBuffer_2_we1;
reg   [10:0] lineBuffer_3_address0;
reg    lineBuffer_3_ce0;
wire   [7:0] lineBuffer_3_q0;
reg   [10:0] lineBuffer_3_address1;
reg    lineBuffer_3_ce1;
reg    lineBuffer_3_we1;
reg   [1:0] lastLine_reg_313;
reg   [10:0] i_reg_324;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state11;
reg   [10:0] lastLine_1_reg_335;
reg   [10:0] i1_reg_347;
reg   [10:0] row_assign_phi_fu_362_p4;
wire   [31:0] i_cast_fu_456_p1;
wire   [31:0] row_assign_cast8_fu_612_p1;
wire  signed [31:0] tmp_23_cast_fu_664_p1;
wire   [31:0] tmp_23_0_2_cast_fu_685_p1;
wire   [31:0] tmp_37_fu_445_p2;
wire   [31:0] tmp_49_fu_581_p2;
reg    ap_reg_ioackin_gmem_ARREADY;
reg    ap_sig_ioackin_gmem_ARREADY;
reg    ap_reg_ioackin_gmem2_AWREADY;
reg    ap_reg_ioackin_gmem2_WREADY;
wire    ap_block_pp0_stage0_flag00001001;
wire   [29:0] out_pix3_fu_379_p4;
wire   [12:0] tmp_26_fu_393_p3;
wire   [8:0] tmp_30_fu_405_p3;
wire   [13:0] p_shl5_cast_fu_401_p1;
wire   [13:0] p_shl6_cast_fu_413_p1;
wire   [13:0] tmp_31_fu_417_p2;
wire  signed [31:0] tmp_36_fu_441_p1;
wire   [21:0] tmp_38_fu_474_p3;
wire   [17:0] tmp_39_fu_486_p3;
wire   [22:0] p_shl9_cast_fu_482_p1;
wire   [22:0] p_shl2_cast_fu_494_p1;
wire   [21:0] tmp_41_fu_504_p3;
wire   [17:0] tmp_42_fu_516_p3;
wire   [22:0] p_shl7_cast_fu_512_p1;
wire   [22:0] p_shl8_cast_fu_524_p1;
wire   [0:0] tmp_3_fu_546_p2;
wire   [0:0] tmp_4_fu_552_p2;
wire   [22:0] tmp_43_fu_528_p2;
wire  signed [31:0] tmp_46_fu_568_p1;
wire   [22:0] tmp_40_fu_498_p2;
wire  signed [31:0] tmp_48_fu_577_p1;
wire   [0:0] tmp_s_fu_636_p2;
wire   [0:0] tmp_7_fu_642_p2;
wire   [0:0] tmp2_fu_648_p2;
wire   [11:0] tmp_14_fu_659_p2;
wire   [7:0] tmp_17_fu_705_p6;
wire   [7:0] tmp_19_fu_722_p6;
wire   [8:0] tmp_24_0_2_cast_fu_735_p1;
wire   [8:0] tmp_241_cast_fu_718_p1;
wire   [8:0] tmp_28_0_1_fu_777_p3;
wire   [8:0] p_shl1_fu_791_p3;
wire  signed [10:0] x_weight_0_2_cast_fu_788_p1;
wire   [10:0] p_shl1_cast_fu_798_p1;
wire   [7:0] tmp_22_fu_808_p6;
wire   [8:0] tmp_26_1_2_fu_817_p3;
wire   [10:0] tmp_26_1_2_cast_fu_825_p1;
wire   [10:0] x_weight_1_1_fu_802_p2;
wire   [9:0] tmp_28_0_1_cast_fu_784_p1;
wire   [9:0] tmp3_cast_fu_835_p1;
wire   [9:0] y_weight_1_2_fu_838_p2;
wire   [10:0] x_weight_1_2_fu_829_p2;
wire   [10:0] tmp_24_2_cast_fu_848_p1;
wire   [10:0] y_weight_1_2_cast_fu_844_p1;
wire   [8:0] p_shl_fu_863_p3;
wire   [10:0] y_weight_2_fu_857_p2;
wire   [10:0] p_shl_cast_fu_870_p1;
wire   [7:0] tmp_25_fu_880_p6;
wire   [10:0] x_weight_2_fu_851_p2;
wire   [10:0] tmp_24_2_2_cast_fu_889_p1;
wire   [10:0] y_weight_2_1_fu_874_p2;
wire   [7:0] tmp_50_fu_893_p1;
wire   [0:0] tmp_9_fu_919_p2;
wire   [7:0] tmp_28_fu_924_p2;
wire   [0:0] tmp_12_fu_936_p2;
wire   [7:0] tmp_32_fu_941_p2;
wire   [7:0] tmp_33_fu_946_p3;
wire   [7:0] tmp_29_fu_929_p3;
wire   [0:0] tmp_20_fu_969_p2;
wire   [7:0] edge_val_fu_959_p2;
wire   [0:0] not_or_cond2_fu_982_p2;
wire   [0:0] tmp_16_fu_964_p2;
wire   [0:0] tmp_35_fu_995_p2;
wire   [7:0] edge_val_1_i_cast_fu_987_p3;
wire   [7:0] p_i_fu_974_p3;
reg   [25:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 26'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_reg_ioackin_gmem_ARREADY = 1'b0;
#0 ap_reg_ioackin_gmem2_AWREADY = 1'b0;
#0 ap_reg_ioackin_gmem2_WREADY = 1'b0;
end

sobel_filter_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
sobel_filter_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .inter_pix(inter_pix),
    .out_pix(out_pix)
);

sobel_filter_gmem_m_axi #(
    .USER_DW( 8 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
sobel_filter_gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARID(1'd0),
    .I_ARLEN(32'd1920),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(8'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(1'd0),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

sobel_filter_gmem2_m_axi #(
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ))
sobel_filter_gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem2_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem2_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem2_RDATA),
    .I_RID(gmem2_RID),
    .I_RUSER(gmem2_RUSER),
    .I_RRESP(gmem2_RRESP),
    .I_RLAST(gmem2_RLAST),
    .I_AWVALID(gmem2_AWVALID),
    .I_AWREADY(gmem2_AWREADY),
    .I_AWADDR(tmp_47_reg_1091),
    .I_AWID(1'd0),
    .I_AWLEN(32'd1920),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(gmem2_WVALID),
    .I_WREADY(gmem2_WREADY),
    .I_WDATA(gmem2_WDATA),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem2_BVALID),
    .I_BREADY(gmem2_BREADY),
    .I_BRESP(gmem2_BRESP),
    .I_BID(gmem2_BID),
    .I_BUSER(gmem2_BUSER)
);

sobel_filter_linebkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
lineBuffer_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(lineBuffer_0_address0),
    .ce0(lineBuffer_0_ce0),
    .we0(lineBuffer_0_we0),
    .d0(reg_369),
    .q0(lineBuffer_0_q0),
    .address1(lineBuffer_0_address1),
    .ce1(lineBuffer_0_ce1),
    .we1(lineBuffer_0_we1),
    .d1(reg_369),
    .q1(lineBuffer_0_q1)
);

sobel_filter_linebkb #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
lineBuffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(lineBuffer_1_address0),
    .ce0(lineBuffer_1_ce0),
    .we0(lineBuffer_1_we0),
    .d0(reg_369),
    .q0(lineBuffer_1_q0),
    .address1(lineBuffer_1_address1),
    .ce1(lineBuffer_1_ce1),
    .we1(lineBuffer_1_we1),
    .d1(reg_369),
    .q1(lineBuffer_1_q1)
);

sobel_filter_linedEe #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
lineBuffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(lineBuffer_2_address0),
    .ce0(lineBuffer_2_ce0),
    .q0(lineBuffer_2_q0),
    .address1(lineBuffer_2_address1),
    .ce1(lineBuffer_2_ce1),
    .we1(lineBuffer_2_we1),
    .d1(reg_369),
    .q1(lineBuffer_2_q1)
);

sobel_filter_linedEe #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
lineBuffer_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(lineBuffer_3_address0),
    .ce0(lineBuffer_3_ce0),
    .q0(lineBuffer_3_q0),
    .address1(lineBuffer_3_address1),
    .ce1(lineBuffer_3_ce1),
    .we1(lineBuffer_3_we1),
    .d1(reg_369),
    .q1(lineBuffer_3_q1)
);

sobel_filter_mux_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_filter_mux_fYi_U0(
    .din1(lineBuffer_0_q0),
    .din2(lineBuffer_1_q0),
    .din3(lineBuffer_2_q0),
    .din4(lineBuffer_3_q0),
    .din5(tmp_19_0_t_reg_1106),
    .dout(tmp_18_fu_672_p6)
);

sobel_filter_mux_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_filter_mux_fYi_U1(
    .din1(lineBuffer_0_q0),
    .din2(lineBuffer_1_q0),
    .din3(lineBuffer_2_q0),
    .din4(lineBuffer_3_q0),
    .din5(tmp_19_2_t_reg_1113),
    .dout(tmp_24_fu_692_p6)
);

sobel_filter_mux_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_filter_mux_fYi_U2(
    .din1(lineBuffer_0_q1),
    .din2(lineBuffer_1_q1),
    .din3(lineBuffer_2_q0),
    .din4(lineBuffer_3_q0),
    .din5(tmp_19_0_t_reg_1106),
    .dout(tmp_17_fu_705_p6)
);

sobel_filter_mux_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_filter_mux_fYi_U3(
    .din1(lineBuffer_0_q0),
    .din2(lineBuffer_1_q0),
    .din3(lineBuffer_2_q1),
    .din4(lineBuffer_3_q1),
    .din5(tmp_19_0_t_reg_1106),
    .dout(tmp_19_fu_722_p6)
);

sobel_filter_mux_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_filter_mux_fYi_U4(
    .din1(lineBuffer_0_q1),
    .din2(lineBuffer_1_q1),
    .din3(lineBuffer_2_q0),
    .din4(lineBuffer_3_q0),
    .din5(tmp_45_reg_1078),
    .dout(tmp_21_fu_745_p6)
);

sobel_filter_mux_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_filter_mux_fYi_U5(
    .din1(lineBuffer_0_q1),
    .din2(lineBuffer_1_q1),
    .din3(lineBuffer_2_q0),
    .din4(lineBuffer_3_q0),
    .din5(tmp_19_2_t_reg_1113),
    .dout(tmp_23_fu_764_p6)
);

sobel_filter_mux_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_filter_mux_fYi_U6(
    .din1(lineBuffer_0_load_2_reg_1220),
    .din2(lineBuffer_1_load_2_reg_1226),
    .din3(lineBuffer_2_load_2_reg_1232),
    .din4(lineBuffer_3_load_2_reg_1238),
    .din5(tmp_45_reg_1078),
    .dout(tmp_22_fu_808_p6)
);

sobel_filter_mux_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_filter_mux_fYi_U7(
    .din1(lineBuffer_0_load_2_reg_1220),
    .din2(lineBuffer_1_load_2_reg_1226),
    .din3(lineBuffer_2_load_2_reg_1232),
    .din4(lineBuffer_3_load_2_reg_1238),
    .din5(tmp_19_2_t_reg_1113),
    .dout(tmp_25_fu_880_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter0_state20))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state19) & (ap_sig_ioackin_gmem2_AWREADY == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011011 == 1'b0))) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state20)) begin
                ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state20 ^ 1'b1);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011011 == 1'b0))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011011 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011011 == 1'b0)))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((1'b1 == ap_CS_fsm_state19) & (ap_sig_ioackin_gmem2_AWREADY == 1'b1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem2_AWREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            if ((ap_sig_ioackin_gmem2_AWREADY == 1'b1)) begin
                ap_reg_ioackin_gmem2_AWREADY <= 1'b0;
            end else if ((1'b1 == gmem2_AWREADY)) begin
                ap_reg_ioackin_gmem2_AWREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem2_WREADY <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter3))) begin
            if ((ap_block_pp0_stage0_flag00011001 == 1'b0)) begin
                ap_reg_ioackin_gmem2_WREADY <= 1'b0;
            end else if (((1'b1 == gmem2_WREADY) & (ap_block_pp0_stage0_flag00001001 == 1'b0))) begin
                ap_reg_ioackin_gmem2_WREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_ARREADY <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state3) & (ap_sig_ioackin_gmem_ARREADY == 1'b1)) | ((1'b1 == ap_CS_fsm_state13) & (ap_sig_ioackin_gmem_ARREADY == 1'b1)))) begin
            ap_reg_ioackin_gmem_ARREADY <= 1'b0;
        end else if ((((1'b1 == ap_CS_fsm_state3) & (1'b1 == gmem_ARREADY)) | ((1'b1 == ap_CS_fsm_state13) & (1'b1 == gmem_ARREADY)))) begin
            ap_reg_ioackin_gmem_ARREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_423_p2 == 1'd1))) begin
        i1_reg_347 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state31) & (gmem2_BVALID == 1'b1))) begin
        i1_reg_347 <= i_2_reg_1073;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        i_reg_324 <= i_1_reg_1055;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        i_reg_324 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_423_p2 == 1'd1))) begin
        lastLine_1_reg_335 <= 11'd2;
    end else if (((1'b1 == ap_CS_fsm_state31) & (gmem2_BVALID == 1'b1))) begin
        lastLine_1_reg_335 <= lastLine_2_reg_1301;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & ~((tmp_2_fu_462_p2 == 1'd0) & (1'b0 == gmem_RVALID)) & (tmp_2_fu_462_p2 == 1'd1))) begin
        lastLine_reg_313 <= tmp_6_reg_1037;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        lastLine_reg_313 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == tmp_8_reg_1130) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        row_assign_reg_358 <= j_reg_1134;
    end else if (((1'b1 == ap_CS_fsm_state19) & (ap_sig_ioackin_gmem2_AWREADY == 1'b1))) begin
        row_assign_reg_358 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        ap_reg_pp0_iter1_or_cond2_reg_1140 <= or_cond2_reg_1140;
        ap_reg_pp0_iter2_or_cond2_reg_1140 <= ap_reg_pp0_iter1_or_cond2_reg_1140;
        row_assign_cast_reg_1125[10 : 0] <= row_assign_cast_fu_620_p1[10 : 0];
        tmp3_reg_1254 <= tmp3_fu_758_p2;
        tmp_15_reg_1286 <= tmp_15_fu_953_p2;
        tmp_21_reg_1249 <= tmp_21_fu_745_p6;
        tmp_23_reg_1259 <= tmp_23_fu_764_p6;
        tmp_8_reg_1130 <= tmp_8_fu_624_p2;
        x_weight_0_2_reg_1244 <= x_weight_0_2_fu_739_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'd0 == tmp_fu_423_p2))) begin
        cond_reg_1042 <= cond_fu_435_p2;
        gmem_addr_reg_1046 <= tmp_37_fu_445_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (1'd0 == tmp_1_fu_534_p2))) begin
        gmem_addr_1_reg_1096 <= tmp_49_fu_581_p2;
        tmp1_reg_1086 <= tmp1_fu_562_p2;
        tmp_45_reg_1078 <= tmp_45_fu_558_p1;
        tmp_47_reg_1091 <= tmp_47_fu_572_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & ~((tmp_2_fu_462_p2 == 1'd0) & (1'b0 == gmem_RVALID)))) begin
        i_1_reg_1055 <= i_1_fu_468_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        i_2_reg_1073 <= i_2_fu_540_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        inter_pix_read_reg_1023 <= inter_pix;
        tmp_13_reg_1029[29 : 0] <= tmp_13_fu_389_p1[29 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        j_reg_1134 <= j_fu_630_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        lastLine_2_reg_1301 <= lastLine_2_fu_1017_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == tmp_8_fu_624_p2))) begin
        lineBuffer_0_addr_2_reg_1146 <= row_assign_cast8_fu_612_p1;
        lineBuffer_1_addr_2_reg_1152 <= row_assign_cast8_fu_612_p1;
        lineBuffer_2_addr_1_reg_1158 <= row_assign_cast8_fu_612_p1;
        lineBuffer_3_addr_1_reg_1164 <= row_assign_cast8_fu_612_p1;
        or_cond2_reg_1140 <= or_cond2_fu_654_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (tmp_2_fu_462_p2 == 1'd0) & ~((tmp_2_fu_462_p2 == 1'd0) & (1'b0 == gmem_RVALID)))) begin
        lineBuffer_0_addr_reg_1060 <= i_cast_fu_456_p1;
        lineBuffer_1_addr_reg_1065 <= i_cast_fu_456_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        lineBuffer_0_load_2_reg_1220 <= lineBuffer_0_q0;
        lineBuffer_1_load_2_reg_1226 <= lineBuffer_1_q0;
        lineBuffer_2_load_2_reg_1232 <= lineBuffer_2_q1;
        lineBuffer_3_load_2_reg_1238 <= lineBuffer_3_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state10) & (tmp_2_fu_462_p2 == 1'd0) & ~((tmp_2_fu_462_p2 == 1'd0) & (1'b0 == gmem_RVALID))) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == tmp_8_reg_1130) & (ap_block_pp0_stage1_flag00011001 == 1'b0)))) begin
        reg_369 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'd0 == tmp_8_reg_1130) & (ap_block_pp0_stage1_flag00011001 == 1'b0))) begin
        tmp_18_reg_1190 <= tmp_18_fu_672_p6;
        tmp_24_reg_1215 <= tmp_24_fu_692_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state19) & (ap_sig_ioackin_gmem2_AWREADY == 1'b1))) begin
        tmp_19_0_t_reg_1106 <= tmp_19_0_t_fu_596_p2;
        tmp_19_2_t_reg_1113 <= tmp_19_2_t_fu_601_p2;
        tmp_44_reg_1102 <= tmp_44_fu_592_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0))) begin
        tmp_27_reg_1274 <= tmp_27_fu_909_p2;
        tmp_51_reg_1280 <= tmp_51_fu_915_p1;
        val_reg_1293 <= val_fu_1000_p3;
        x_weight_2_2_reg_1264 <= x_weight_2_2_fu_897_p2;
        y_weight_2_2_reg_1269 <= y_weight_2_2_fu_903_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_6_reg_1037 <= tmp_6_fu_429_p2;
    end
end

always @ (*) begin
    if ((tmp_8_fu_624_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state20 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state20 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (tmp_1_fu_534_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_enable_reg_pp0_iter3))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (tmp_1_fu_534_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_gmem2_AWREADY)) begin
        ap_sig_ioackin_gmem2_AWREADY = gmem2_AWREADY;
    end else begin
        ap_sig_ioackin_gmem2_AWREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_gmem2_WREADY)) begin
        ap_sig_ioackin_gmem2_WREADY = gmem2_WREADY;
    end else begin
        ap_sig_ioackin_gmem2_WREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_gmem_ARREADY)) begin
        ap_sig_ioackin_gmem_ARREADY = gmem_ARREADY;
    end else begin
        ap_sig_ioackin_gmem_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & (1'b0 == ap_reg_ioackin_gmem2_AWREADY))) begin
        gmem2_AWVALID = 1'b1;
    end else begin
        gmem2_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) & (gmem2_BVALID == 1'b1))) begin
        gmem2_BREADY = 1'b1;
    end else begin
        gmem2_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b0 == ap_reg_ioackin_gmem2_WREADY))) begin
        gmem2_WVALID = 1'b1;
    end else begin
        gmem2_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        gmem2_blk_n_AW = m_axi_gmem2_AWREADY;
    end else begin
        gmem2_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        gmem2_blk_n_B = m_axi_gmem2_BVALID;
    end else begin
        gmem2_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
        gmem2_blk_n_W = m_axi_gmem2_WREADY;
    end else begin
        gmem2_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_gmem_ARREADY)) begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            gmem_ARADDR = gmem_addr_1_reg_1096;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            gmem_ARADDR = gmem_addr_reg_1046;
        end else begin
            gmem_ARADDR = 'bx;
        end
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (1'b0 == ap_reg_ioackin_gmem_ARREADY)) | ((1'b1 == ap_CS_fsm_state13) & (1'b0 == ap_reg_ioackin_gmem_ARREADY)))) begin
        gmem_ARVALID = 1'b1;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state10) & (tmp_2_fu_462_p2 == 1'd0) & ~((tmp_2_fu_462_p2 == 1'd0) & (1'b0 == gmem_RVALID))) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == tmp_8_reg_1130) & (ap_block_pp0_stage1_flag00011001 == 1'b0)))) begin
        gmem_RREADY = 1'b1;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state10) & (tmp_2_fu_462_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00000000 == 1'b0) & (1'd0 == tmp_8_reg_1130)))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00000000 == 1'b0))) begin
        lineBuffer_0_address0 = tmp_23_0_2_cast_fu_685_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
        lineBuffer_0_address0 = row_assign_cast8_fu_612_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        lineBuffer_0_address0 = lineBuffer_0_addr_reg_1060;
    end else begin
        lineBuffer_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        lineBuffer_0_address1 = lineBuffer_0_addr_2_reg_1146;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00000000 == 1'b0))) begin
        lineBuffer_0_address1 = tmp_23_cast_fu_664_p1;
    end else begin
        lineBuffer_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0)) | (1'b1 == ap_CS_fsm_state11))) begin
        lineBuffer_0_ce0 = 1'b1;
    end else begin
        lineBuffer_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00011001 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1)))) begin
        lineBuffer_0_ce1 = 1'b1;
    end else begin
        lineBuffer_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (cond_reg_1042 == 1'd1))) begin
        lineBuffer_0_we0 = 1'b1;
    end else begin
        lineBuffer_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (tmp_44_reg_1102 == 2'd0))) begin
        lineBuffer_0_we1 = 1'b1;
    end else begin
        lineBuffer_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00000000 == 1'b0))) begin
        lineBuffer_1_address0 = tmp_23_0_2_cast_fu_685_p1;
    end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
        lineBuffer_1_address0 = row_assign_cast8_fu_612_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        lineBuffer_1_address0 = lineBuffer_1_addr_reg_1065;
    end else begin
        lineBuffer_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        lineBuffer_1_address1 = lineBuffer_1_addr_2_reg_1152;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00000000 == 1'b0))) begin
        lineBuffer_1_address1 = tmp_23_cast_fu_664_p1;
    end else begin
        lineBuffer_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0)) | (1'b1 == ap_CS_fsm_state11))) begin
        lineBuffer_1_ce0 = 1'b1;
    end else begin
        lineBuffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00011001 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1)))) begin
        lineBuffer_1_ce1 = 1'b1;
    end else begin
        lineBuffer_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (1'd0 == cond_reg_1042))) begin
        lineBuffer_1_we0 = 1'b1;
    end else begin
        lineBuffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (tmp_44_reg_1102 == 2'd1))) begin
        lineBuffer_1_we1 = 1'b1;
    end else begin
        lineBuffer_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00000000 == 1'b0))) begin
            lineBuffer_2_address0 = tmp_23_cast_fu_664_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
            lineBuffer_2_address0 = row_assign_cast8_fu_612_p1;
        end else begin
            lineBuffer_2_address0 = 'bx;
        end
    end else begin
        lineBuffer_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        lineBuffer_2_address1 = lineBuffer_2_addr_1_reg_1158;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00000000 == 1'b0))) begin
        lineBuffer_2_address1 = tmp_23_0_2_cast_fu_685_p1;
    end else begin
        lineBuffer_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0)))) begin
        lineBuffer_2_ce0 = 1'b1;
    end else begin
        lineBuffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00011001 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1)))) begin
        lineBuffer_2_ce1 = 1'b1;
    end else begin
        lineBuffer_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (tmp_44_reg_1102 == 2'd2))) begin
        lineBuffer_2_we1 = 1'b1;
    end else begin
        lineBuffer_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter0)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00000000 == 1'b0))) begin
            lineBuffer_3_address0 = tmp_23_cast_fu_664_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
            lineBuffer_3_address0 = row_assign_cast8_fu_612_p1;
        end else begin
            lineBuffer_3_address0 = 'bx;
        end
    end else begin
        lineBuffer_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        lineBuffer_3_address1 = lineBuffer_3_addr_1_reg_1164;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00000000 == 1'b0))) begin
        lineBuffer_3_address1 = tmp_23_0_2_cast_fu_685_p1;
    end else begin
        lineBuffer_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0)))) begin
        lineBuffer_3_ce0 = 1'b1;
    end else begin
        lineBuffer_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage1_flag00011001 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1)))) begin
        lineBuffer_3_ce1 = 1'b1;
    end else begin
        lineBuffer_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (tmp_44_reg_1102 == 2'd3))) begin
        lineBuffer_3_we1 = 1'b1;
    end else begin
        lineBuffer_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd0 == tmp_8_reg_1130) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        row_assign_phi_fu_362_p4 = j_reg_1134;
    end else begin
        row_assign_phi_fu_362_p4 = row_assign_reg_358;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_423_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (ap_sig_ioackin_gmem_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & ~((tmp_2_fu_462_p2 == 1'd0) & (1'b0 == gmem_RVALID)) & (tmp_2_fu_462_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state10) & (tmp_2_fu_462_p2 == 1'd0) & ~((tmp_2_fu_462_p2 == 1'd0) & (1'b0 == gmem_RVALID)))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (tmp_1_fu_534_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (ap_sig_ioackin_gmem_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((1'b1 == ap_CS_fsm_state19) & (ap_sig_ioackin_gmem2_AWREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_block_pp0_stage0_flag00011011 == 1'b0) & ~((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0)) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (tmp_8_fu_624_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (tmp_8_fu_624_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((ap_block_pp0_stage1_flag00011011 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((1'b1 == ap_CS_fsm_state31) & (gmem2_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0_flag00000000 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_flag00001001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_flag00011001 = ((1'b1 == ap_enable_reg_pp0_iter3) & (1'b0 == ap_sig_ioackin_gmem2_WREADY));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011011 = ((1'b1 == ap_enable_reg_pp0_iter3) & (1'b0 == ap_sig_ioackin_gmem2_WREADY));
end

assign ap_block_pp0_stage1_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_flag00011001 = ((1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == tmp_8_reg_1130) & (1'b0 == gmem_RVALID));
end

always @ (*) begin
    ap_block_pp0_stage1_flag00011011 = ((1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == tmp_8_reg_1130) & (1'b0 == gmem_RVALID));
end

always @ (*) begin
    ap_block_state10 = ((tmp_2_fu_462_p2 == 1'd0) & (1'b0 == gmem_RVALID));
end

assign ap_block_state20_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state21_pp0_stage1_iter0 = ((1'd0 == tmp_8_reg_1130) & (1'b0 == gmem_RVALID));
end

assign ap_block_state22_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cond_fu_435_p2 = ((lastLine_reg_313 == 2'd0) ? 1'b1 : 1'b0);

assign edge_val_1_i_cast_fu_987_p3 = ((not_or_cond2_fu_982_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign edge_val_fu_959_p2 = (tmp_15_reg_1286 ^ 8'd255);

assign gmem2_WDATA = {{{{val_reg_1293}, {val_reg_1293}}, {val_reg_1293}}, {val_reg_1293}};

assign i_1_fu_468_p2 = (i_reg_324 + 11'd1);

assign i_2_fu_540_p2 = (i1_reg_347 + 11'd1);

assign i_cast_fu_456_p1 = i_reg_324;

assign j_fu_630_p2 = (row_assign_phi_fu_362_p4 + 11'd1);

assign lastLine_2_fu_1017_p2 = (lastLine_1_reg_335 + 11'd1);

assign not_or_cond2_fu_982_p2 = (ap_reg_pp0_iter2_or_cond2_reg_1140 ^ 1'd1);

assign or_cond2_fu_654_p2 = (tmp2_fu_648_p2 | tmp1_reg_1086);

assign out_pix3_fu_379_p4 = {{out_pix[31:2]}};

assign p_i_fu_974_p3 = ((tmp_20_fu_969_p2[0:0] === 1'b1) ? 8'd0 : edge_val_fu_959_p2);

assign p_shl1_cast_fu_798_p1 = p_shl1_fu_791_p3;

assign p_shl1_fu_791_p3 = {{tmp_21_reg_1249}, {1'd0}};

assign p_shl2_cast_fu_494_p1 = tmp_39_fu_486_p3;

assign p_shl5_cast_fu_401_p1 = tmp_26_fu_393_p3;

assign p_shl6_cast_fu_413_p1 = tmp_30_fu_405_p3;

assign p_shl7_cast_fu_512_p1 = tmp_41_fu_504_p3;

assign p_shl8_cast_fu_524_p1 = tmp_42_fu_516_p3;

assign p_shl9_cast_fu_482_p1 = tmp_38_fu_474_p3;

assign p_shl_cast_fu_870_p1 = p_shl_fu_863_p3;

assign p_shl_fu_863_p3 = {{tmp_24_reg_1215}, {1'd0}};

assign row_assign_cast8_fu_612_p1 = row_assign_phi_fu_362_p4;

assign row_assign_cast_fu_620_p1 = row_assign_phi_fu_362_p4;

assign tmp1_fu_562_p2 = (tmp_3_fu_546_p2 | tmp_4_fu_552_p2);

assign tmp2_fu_648_p2 = (tmp_s_fu_636_p2 | tmp_7_fu_642_p2);

assign tmp3_cast_fu_835_p1 = tmp3_reg_1254;

assign tmp3_fu_758_p2 = (tmp_24_0_2_cast_fu_735_p1 + tmp_241_cast_fu_718_p1);

assign tmp_12_fu_936_p2 = (($signed(y_weight_2_2_reg_1269) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign tmp_13_fu_389_p1 = out_pix3_fu_379_p4;

assign tmp_14_fu_659_p2 = ($signed(12'd4095) + $signed(row_assign_cast_reg_1125));

assign tmp_15_fu_953_p2 = (tmp_33_fu_946_p3 + tmp_29_fu_929_p3);

assign tmp_16_fu_964_p2 = ((tmp_15_reg_1286 < 8'd55) ? 1'b1 : 1'b0);

assign tmp_19_0_t_fu_596_p2 = ($signed(2'd3) + $signed(tmp_45_reg_1078));

assign tmp_19_2_t_fu_601_p2 = (2'd1 + tmp_45_reg_1078);

assign tmp_1_fu_534_p2 = ((i1_reg_347 == 11'd1080) ? 1'b1 : 1'b0);

assign tmp_20_fu_969_p2 = ((tmp_15_reg_1286 > 8'd155) ? 1'b1 : 1'b0);

assign tmp_23_0_2_cast_fu_685_p1 = j_reg_1134;

assign tmp_23_cast_fu_664_p1 = $signed(tmp_14_fu_659_p2);

assign tmp_241_cast_fu_718_p1 = tmp_17_fu_705_p6;

assign tmp_24_0_2_cast_fu_735_p1 = tmp_19_fu_722_p6;

assign tmp_24_2_2_cast_fu_889_p1 = tmp_25_fu_880_p6;

assign tmp_24_2_cast_fu_848_p1 = tmp_23_reg_1259;

assign tmp_26_1_2_cast_fu_825_p1 = tmp_26_1_2_fu_817_p3;

assign tmp_26_1_2_fu_817_p3 = {{tmp_22_fu_808_p6}, {1'd0}};

assign tmp_26_fu_393_p3 = {{lastLine_reg_313}, {11'd0}};

assign tmp_27_fu_909_p2 = (tmp_50_fu_893_p1 + tmp_25_fu_880_p6);

assign tmp_28_0_1_cast_fu_784_p1 = tmp_28_0_1_fu_777_p3;

assign tmp_28_0_1_fu_777_p3 = {{tmp_18_reg_1190}, {1'd0}};

assign tmp_28_fu_924_p2 = (8'd0 - tmp_27_reg_1274);

assign tmp_29_fu_929_p3 = ((tmp_9_fu_919_p2[0:0] === 1'b1) ? tmp_27_reg_1274 : tmp_28_fu_924_p2);

assign tmp_2_fu_462_p2 = ((i_reg_324 == 11'd1920) ? 1'b1 : 1'b0);

assign tmp_30_fu_405_p3 = {{lastLine_reg_313}, {7'd0}};

assign tmp_31_fu_417_p2 = (p_shl5_cast_fu_401_p1 - p_shl6_cast_fu_413_p1);

assign tmp_32_fu_941_p2 = (8'd0 - tmp_51_reg_1280);

assign tmp_33_fu_946_p3 = ((tmp_12_fu_936_p2[0:0] === 1'b1) ? tmp_51_reg_1280 : tmp_32_fu_941_p2);

assign tmp_35_fu_995_p2 = (ap_reg_pp0_iter2_or_cond2_reg_1140 | tmp_16_fu_964_p2);

assign tmp_36_fu_441_p1 = $signed(tmp_31_fu_417_p2);

assign tmp_37_fu_445_p2 = ($signed(tmp_36_fu_441_p1) + $signed(inter_pix_read_reg_1023));

assign tmp_38_fu_474_p3 = {{lastLine_1_reg_335}, {11'd0}};

assign tmp_39_fu_486_p3 = {{lastLine_1_reg_335}, {7'd0}};

assign tmp_3_fu_546_p2 = ((i1_reg_347 == 11'd0) ? 1'b1 : 1'b0);

assign tmp_40_fu_498_p2 = (p_shl9_cast_fu_482_p1 - p_shl2_cast_fu_494_p1);

assign tmp_41_fu_504_p3 = {{i1_reg_347}, {11'd0}};

assign tmp_42_fu_516_p3 = {{i1_reg_347}, {7'd0}};

assign tmp_43_fu_528_p2 = (p_shl7_cast_fu_512_p1 - p_shl8_cast_fu_524_p1);

assign tmp_44_fu_592_p1 = lastLine_1_reg_335[1:0];

assign tmp_45_fu_558_p1 = i1_reg_347[1:0];

assign tmp_46_fu_568_p1 = $signed(tmp_43_fu_528_p2);

assign tmp_47_fu_572_p2 = ($signed(tmp_46_fu_568_p1) + $signed(tmp_13_reg_1029));

assign tmp_48_fu_577_p1 = $signed(tmp_40_fu_498_p2);

assign tmp_49_fu_581_p2 = ($signed(inter_pix_read_reg_1023) + $signed(tmp_48_fu_577_p1));

assign tmp_4_fu_552_p2 = ((i1_reg_347 == 11'd1079) ? 1'b1 : 1'b0);

assign tmp_50_fu_893_p1 = x_weight_2_fu_851_p2[7:0];

assign tmp_51_fu_915_p1 = y_weight_2_2_fu_903_p2[7:0];

assign tmp_6_fu_429_p2 = (lastLine_reg_313 + 2'd1);

assign tmp_7_fu_642_p2 = ((row_assign_phi_fu_362_p4 == 11'd1919) ? 1'b1 : 1'b0);

assign tmp_8_fu_624_p2 = ((row_assign_phi_fu_362_p4 == 11'd1920) ? 1'b1 : 1'b0);

assign tmp_9_fu_919_p2 = (($signed(x_weight_2_2_reg_1264) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign tmp_fu_423_p2 = ((lastLine_reg_313 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_s_fu_636_p2 = ((row_assign_phi_fu_362_p4 == 11'd0) ? 1'b1 : 1'b0);

assign val_fu_1000_p3 = ((tmp_35_fu_995_p2[0:0] === 1'b1) ? edge_val_1_i_cast_fu_987_p3 : p_i_fu_974_p3);

assign x_weight_0_2_cast_fu_788_p1 = $signed(x_weight_0_2_reg_1244);

assign x_weight_0_2_fu_739_p2 = (tmp_24_0_2_cast_fu_735_p1 - tmp_241_cast_fu_718_p1);

assign x_weight_1_1_fu_802_p2 = ($signed(x_weight_0_2_cast_fu_788_p1) - $signed(p_shl1_cast_fu_798_p1));

assign x_weight_1_2_fu_829_p2 = (tmp_26_1_2_cast_fu_825_p1 + x_weight_1_1_fu_802_p2);

assign x_weight_2_2_fu_897_p2 = (tmp_24_2_2_cast_fu_889_p1 + x_weight_2_fu_851_p2);

assign x_weight_2_fu_851_p2 = (x_weight_1_2_fu_829_p2 - tmp_24_2_cast_fu_848_p1);

assign y_weight_1_2_cast_fu_844_p1 = y_weight_1_2_fu_838_p2;

assign y_weight_1_2_fu_838_p2 = (tmp_28_0_1_cast_fu_784_p1 + tmp3_cast_fu_835_p1);

assign y_weight_2_1_fu_874_p2 = (y_weight_2_fu_857_p2 - p_shl_cast_fu_870_p1);

assign y_weight_2_2_fu_903_p2 = (y_weight_2_1_fu_874_p2 - tmp_24_2_2_cast_fu_889_p1);

assign y_weight_2_fu_857_p2 = (y_weight_1_2_cast_fu_844_p1 - tmp_24_2_cast_fu_848_p1);

always @ (posedge ap_clk) begin
    tmp_13_reg_1029[31:30] <= 2'b00;
    row_assign_cast_reg_1125[11] <= 1'b0;
end

endmodule //sobel_filter
